Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Mi Primer Workflow
+name: Validar index.html
 
 on:
   push:
@@ -6,9 +6,18 @@ on:
       - main
 
 jobs:
-  saludo:
+  validar-html:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Mostrar mensaje
-        run: echo "se hizo un push a la rama main"
+      - name: Descargar repositorio
+        uses: actions/checkout@v4
+
+      - name: Verificar existencia de index.html
+        run: |
+          if [ -f index.html ]; then
+            echo " index.html existe"
+          else
+            echo " Error: index.html no existe"
+            exit 1
+          fi
